### ISSUE TITLE
spark new repl: Missing dependency 'object scala in compiler mirror'

### ISSUE THREAD

**Issue by ChenZhongPu** [sanjosh/scala#1]
> [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)
> 
> Failed to initialize compiler: object scala in compiler mirror not found.
> ** Note that as of 2.8 scala does not assume use of the java classpath.
> ** For the old behavior pass -usejavacp to scala, or if using a Settings
> ** object programmatically, settings.usejavacp.value = true.
> 
> Failed to initialize compiler: object scala in compiler mirror not found.
> ** Note that as of 2.8 scala does not assume use of the java classpath.
> ** For the old behavior pass -usejavacp to scala, or if using a Settings
> ** object programmatically, settings.usejavacp.value = true.
> Exception in thread "main" java.lang.NullPointerException
> 	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
> 	at scala.tools.nsc.interpreter.IMain$Request.x$20$lzycompute(IMain.scala:896)
> 	at scala.tools.nsc.interpreter.IMain$Request.x$20(IMain.scala:895)
> 	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble$lzycompute(IMain.scala:895)
> 	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble(IMain.scala:895)
> 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.preamble(IMain.scala:918)
> 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1337)
> 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1336)
> 	at scala.tools.nsc.util.package$.stringFromWriter(package.scala:64)
> 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$class.apply(IMain.scala:1336)
> 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.apply(IMain.scala:908)
> 	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:1002)
> 	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:997)
> 	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:579)
> 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:567)
> 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
> 	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
> 	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
> 	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
> 	at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply$mcV$sp(SparkILoop.scala:38)
> 	at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
> 	at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
> 	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
> 	at org.apache.spark.repl.SparkILoop.initializeSpark(SparkILoop.scala:37)
> 	at org.apache.spark.repl.SparkILoop.loadFiles(SparkILoop.scala:105)
> 	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:920)
> 	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
> 	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
> 	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
> 	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
> 	at org.apache.spark.repl.simba.Main$.doMain(Main.scala:48)
> 	at org.apache.spark.repl.simba.Main$.main(Main.scala:32)
> 	at org.apache.spark.repl.simba.Main.main(Main.scala)
> 18/06/29 12:01:31 INFO ShutdownHookManager: Shutdown hook called
> 18/06/29 12:01:31 INFO ShutdownHookManager: Deleting directory /private/var/folders/_g/09q_x1bd5771yjlhg2lbr6qw0000gn/T/spark-6e67749e-8283-4f16-a9e0-31a0957ed492
> 18/06/29 12:01:31 INFO ShutdownHookManager: Deleting directory /private/var/folders/_g/09q_x1bd5771yjlhg2lbr6qw0000gn/T/spark-6e67749e-8283-4f16-a9e0-31a0957ed492/repl-c7f84696-c6f7-400f-9f50-e7dc81d8a7ce
> 
> Process finished with exit code 1
>

**Comment by sanjosh** [comment]
Likely a scala/sbt build issue.  See similar report here
https://github.com/frees-io/freestyle/issues/364

**Comment by ChenZhongPu** [comment]
Yes, I have seen many similar reports, but none of them can solve my problem.

**Comment by Jacke** [comment]
```
scalacOptions += "-Xplugin-require:macroparadise"

scalacOptions in (Compile, console) := Seq() 
```
into build.sbt

**Comment by sanjosh** [comment]
thanks @Jacke
